# Generated by Django 4.2 on 2023-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="doc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
