# Generated by Django 4.2 on 2023-05-30 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_files_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="files",
            name="doc",
        ),
    ]
